---
# tasks file for gradle

- name: create gradle directory
  file: path=/opt/gradle state=directory

- name: download and unzip
  unarchive:
    src: https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
    dest: /opt/gradle
    remote_src: yes
