---
# tasks file for dotfiles

- name: clone my dotfiles repository
  git:
    repo: https://github.com/mattladany/dotfiles.git
    dest: /home/vagrant/dotfiles/
  become_user: vagrant

- name: install
  shell: "printf 'O\n' | install/bootstrap.sh --skip-git"
  args:
    chdir: /home/vagrant/dotfiles/
  become_user: vagrant
