---
# tasks file for devbox

- name: install epel-release
  yum: name=epel-release state=present

- name: install yum-utils
  yum: name=yum-utils state=present

- name: install Development tools
  yum: name="@Development tools" state=present
  notify: update yum packages

- name: install GNOME Desktop
  yum: name="@^gnome-desktop-environment" state=present

# cannot seem to find how to set the defualt systemd target using ansible,
#   so using script for now.
- name: setup graphical target
  script: scripts/set-graphical-target.sh

- name: install ius-release
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: install wanted packages
  yum:
    name: ['wget', 'curl', 'ncurses', 'ncurses-devel', 'python36', 'python36-devel', 'python36-pip', 'cmake', 'gcc-c++', 'make', 'mono-addins-devel', 'java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'ruby', 'ruby-devel']
    state: present

- name: install packages needed for vim
  yum:
    name: ['lua', 'lua-devel', 'luajit', 'luajit-devel', 'ctags', 'python34', 'python34-devel', 'tcl-devel', 'perl', 'perl-devel', 'perl-ExtUtils-XSpp', 'perl-ExtUtils-CBuilder', 'perl-ExtUtils-Embed']
    state: present

- name: install package needed for tmux
  yum: name=libevent-devel state=present

- name: create symlink for xsubpp
  file:
    src: /usr/bin/xsubpp
    dest: /usr/share/perl5/ExtUtils/xsubpp
    state: link
