---
# tasks file for centos7

- name: install yum-utils
  yum: name=yum-utils state=present

- name: install Development tools
  yum: name="@Development tools" state=present
  notify: update yum packages

- name: install the X windowing system
  yum:
    name: "@X Window System"
    state: present

- name: install Xfce
  yum:
    name: "@Xfce"
    state: present

- name: install GNOME Desktop
  yum: name="@^gnome-desktop-environment" state=present

- name: install KDE
  command: yum groupinstall -y "KDE Plasma Workspaces"

- name: set the default run level to runlevel5 (run with GUI)
  file:
    src: /lib/systemd/system/runlevel5.target
    dest: /etc/systemd/system/default.target
    state: link
    force: yes

- name: make sure graphical.target is started
  systemd:
    name: graphical.target
    state: started

- name: install ius-release
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: install wanted packages
  yum:
    name: ['wget', 'curl', 'ncurses', 'ncurses-devel', 'python36', 'python36-devel', 'python36-pip', 'cmake', 'gcc-c++', 'make', 'mono-addins-devel', 'java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'ruby', 'ruby-devel']
    state: present

- name: install packages needed for vim
  yum:
    name: ['lua', 'lua-devel', 'luajit', 'luajit-devel', 'ctags', 'python34', 'python34-devel', 'tcl-devel', 'perl', 'perl-devel', 'perl-ExtUtils-XSpp', 'perl-ExtUtils-CBuilder', 'perl-ExtUtils-Embed']
    state: present

- name: install package needed for tmux
  yum: name=libevent-devel state=present

- name: create symlink for xsubpp
  file:
    src: /usr/bin/xsubpp
    dest: /usr/share/perl5/ExtUtils/xsubpp
    state: link
