---
# tasks file for arch

- name: update and upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: install dev-tools
  pacman:
    name: base-devel
    state: present

    #- name: install kde plasma 5
    #pacman:
    #name: plasma
    #state: present
    #
    #- name: install the plasma display manager
    #pacman:
    #name: ['sddm', 'sddm-kcm']
    #state: present
    #
    #- name: start and enable sddm
    #systemd:
    #name: sddm
    #enabled: yes
    #state: started

- name: install X Window System
  pacman:
    name: ['xorg', 'xorg-server']
    state: present

- name: install gnome
  pacman:
    name: gnome
    state: present

- name: start and enable gdm
  systemd:
    name: gdm
    state: started
    enabled: yes

- name: install wanted/needed packages
  pacman:
    name: ['curl', 'git', 'unzip']
    state: present
