---
# tasks file for arch

- name: update and upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: install dev-tools
  pacman:
    name: base-devel
    state: present

- name: install xorg stuff
  pacman:
    name: ['xorg-server', 'xorg-apps', 'xorg-xinit']
    state: present

- name: uninstall virtualbox-guest-utils-nox
  pacman:
    name: virtualbox-guest-utils-nox
    state: absent

- name: install virtualbox-guest-utils
  pacman:
    name: virtualbox-guest-utils
    state: latest

- name: install kde plasma 5
  pacman:
    name: plasma
    state: present

- name: install the plasma display manager
  pacman:
    name: ['sddm', 'sddm-kcm']
    state: present

- name: start and enable sddm
  systemd:
    name: sddm
    enabled: yes
  notify: restart

- name: install wanted/needed packages
  pacman:
    name: ['curl', 'git', 'unzip']
    state: present
