---
# tasks file for xenial64

- name: update apt packages
  apt:
    name: '*'
    state: latest
    force_apt_get: yes

- name: install ubuntu desktop
  apt:
    name: ubuntu-desktop
    state: present
  notify: reboot

- name: install development tools
  apt:
    name: ['automake', 'build-essential', 'pkg-config', 'libevent-dev', 'libncurses5-dev']
    state: present

- name: install necessary vim packages
  apt:
    name: ['wget', 'git', 'curl', 'libgnome2-dev', 'libgnomeui-dev', 'libgtk2.0-dev', 'libatk1.0-dev', 'libcairo2-dev', 'libx11-dev', 'libxpm-dev', 'libxt-dev', 'python3', 'python3-dev', 'lua5.1', 'liblua5.1-dev', 'libperl-dev', 'cmake', 'make', 'mono-xbuild', 'default-jre', 'default-jdk', 'ruby-dev']
    state: present
